### ISSUE TITLE
Improvement: update to support Specification up to Draft 2020-12

### ISSUE THREAD

**Issue by crcdng** [Workiva/json_schema#81]
The package supports schema up to Draft-07. 
The current version of the Specification Draft is 2020-12.
Update the package to support newer versions.

## Type
Improvement

> __FYI:__ @michaelcarter-wf

**Comment by ShantanuJoshi** [comment]
How are you able to see Draft-07 support? I get an error saying only Draft 4 & 6 are supported

**Comment by i3games** [comment]
https://github.com/Workiva/json_schema/commit/46b1e956b8e7aae20085cd5dba87e701500f99e2

**Comment by michaelcarter-wf** [comment]
I'd love to add additional drafts, but time to work on this project is limited. I'm planning to do 2019-09 next.

**Comment by michaelcarter-wf** [comment]
@crcdng This is done in 4.0! :)

**Comment by ShantanuJoshi** [comment]
Ty @michaelcarter-wf !

**Comment by megalepozy** [comment]
@michaelcarter-wf  The Readme first line says the following:
"A platform agnostic (web, flutter or vm) Dart library for validating JSON instances against JSON Schemas (multi-version support with latest of Draft 7)."

I was on the impression that it support up to Draft 7 and not supporting any version afterward, but since I was curios I decided to check if anyone raised an issue about this and found here that actually all the spec versions r supported.

Maybe it's time to update the first line so people won't see something misleading which probably make lots of users leave the project immediately?
